#!/usr/bin/env python3
"""krkrz_linux: 吉里吉里Z の Linux 版アプリをビルドしてパッケージにまとめる。

    python3 tools/krkrz_linux.py all        # build + stage + package
    python3 tools/krkrz_linux.py build      # sniper コンテナで configure/build/install
    python3 tools/krkrz_linux.py stage      # install + assetPack + .cf/.desktop → package フォルダ
    python3 tools/krkrz_linux.py package    # package フォルダ → tar.gz
    python3 tools/krkrz_linux.py clean

フォルダの決まり (krkrz_android と同じ):
  BUILD_SYSTEM_DIR  このリポジトリ (固定)
  PROJECT_DIR       案件フォルダ (環境変数。未設定ならこのリポジトリ = サンプル案件)
                    ${PROJECT_DIR}/linux-config.json を読み、${PROJECT_DIR}/build/linux/ に出力
  KRKRZ_BASE        krkrz_dev の親フォルダ (環境変数)

標準ライブラリだけで動く (sniper SDK の python3 = 3.9 で動くこと)。
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import stage as stage_engine  # noqa: E402

logger = logging.getLogger("krkrz_linux")

BUILD_SYSTEM_DIR = Path(__file__).resolve().parent.parent
DEFAULT_IMAGE = "deckbuild-sniper"   # steamdev の deckbuild/deckbuild.sh image で作るイメージ
CACHE_VOLUME = "deckbuild-cache"     # vcpkg バイナリキャッシュ (deckbuild と共用)
IN_CONTAINER_ENV = "KRKRZ_LINUX_IN_CONTAINER"


# ---------------------------------------------------------------------------
# 設定
# ---------------------------------------------------------------------------

class Config:
    def __init__(self) -> None:
        self.project_dir = Path(os.environ.get("PROJECT_DIR") or BUILD_SYSTEM_DIR).resolve()
        base = os.environ.get("KRKRZ_BASE")
        if not base:
            sys.exit("KRKRZ_BASE が未設定です (krkrz_dev のある親フォルダを指定)")
        self.krkrz_base = Path(base).resolve()
        if not (self.krkrz_base / "krkrz_dev" / "src" / "core").is_dir():
            sys.exit(f"krkrz_dev が見つかりません: {self.krkrz_base}/krkrz_dev")
        path = self.project_dir / "linux-config.json"
        if not path.is_file():
            sys.exit(f"linux-config.json がありません: {path}")
        with open(path, encoding="utf-8") as f:
            self.raw = json.load(f)
        self.ctx = {
            "PROJECT_DIR": str(self.project_dir),
            "BUILD_SYSTEM_DIR": str(BUILD_SYSTEM_DIR),
            "KRKRZ_BASE": str(self.krkrz_base),
        }

        r = self.raw
        self.name = r.get("name", "krkrz")
        self.version = str(r.get("version", "0.0.0"))
        self.exe_name = r.get("exeName", "krkrz")
        self.org_name = r.get("orgName", "wamsoft")
        self.app_name = r.get("appName", self.exe_name)
        self.arch = r.get("arch", "x64")
        cm = r.get("cmake", {})
        self.build_type = cm.get("buildType", "Release")
        self.preset_triplet = {"x64": "x64-linux", "arm64": "arm64-linux"}[self.arch]

        out = self.project_dir / "build" / "linux"
        self.out_dir = out
        self.generated_dir = out / "generated"
        self.cmake_dir = out / "cmake"
        self.install_dir = out / "install"
        self.package_dir = out / "package" / self.exe_name
        self.dist_dir = out / "dist"

    def expand(self, s: str) -> str:
        return stage_engine.expand_vars(s, self.ctx)


# ---------------------------------------------------------------------------
# 生成物
# ---------------------------------------------------------------------------

def gen_myapp_cmake(cfg: Config) -> Path:
    """cmake セクション → myapp.cmake (krkrz_android の generateMyappCmake と同形式)。"""
    cm = cfg.raw.get("cmake", {})
    lines = ["# generated by krkrz_linux.py from linux-config.json — do not edit", ""]
    for var, key in (("TVP_PLUGIN_FOLDERS", "pluginFolders"),
                     ("TVP_PLUGINS", "plugins"),
                     ("TVP_PLUGINS_STATIC", "staticPlugins")):
        items = [cfg.expand(x) for x in cm.get(key, [])]
        if items:
            lines.append(f"LIST(APPEND {var}")
            lines += [f"    {x}" for x in items]
            lines.append(")")
    path = cfg.generated_dir / "myapp.cmake"
    _write_if_changed(path, "\n".join(lines) + "\n")
    return path


def _tjs_quote(v: str) -> str:
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_package_files(cfg: Config) -> Path:
    """パッケージに入れる生成物 (.cf / .desktop / アイコン) を generated/package に置く。"""
    out = cfg.generated_dir / "package"
    out.mkdir(parents=True, exist_ok=True)
    for p in out.iterdir():
        if p.is_file():
            p.unlink()

    # <exeName>.cf — orgname / appname で Linux のデータ保存場所
    # (~/.local/share/<orgname>/<appname>/) が決まる。Steam Cloud の同期パスもここ
    opts = {"orgname": cfg.org_name, "appname": cfg.app_name}
    opts.update(cfg.raw.get("config", {}).get("options", {}))
    cf = ["; generated by krkrz_linux.py from linux-config.json"]
    cf += [f"{k}={_tjs_quote(str(v))}" for k, v in opts.items()]
    (out / f"{cfg.exe_name}.cf").write_text("\n".join(cf) + "\n", encoding="utf-8")

    # freedesktop の .desktop + アイコン。tar 配布ではインストール時のひな形、
    # AppImage / Flatpak では必須メタデータになる
    d = cfg.raw.get("desktop", {})
    app_id = d.get("id", f"{cfg.org_name}.{cfg.app_name}")
    icon_name = app_id
    icon_src = d.get("icon")
    if icon_src:
        src = Path(cfg.expand(icon_src))
        if not src.is_absolute():
            src = cfg.project_dir / src
        if src.is_file():
            icon_name = app_id
            shutil.copy2(src, out / f"{app_id}{src.suffix}")
        else:
            logger.warning("icon not found: %s", src)
    desktop = [
        "[Desktop Entry]",
        "Type=Application",
        f"Name={cfg.name}",
        f"Comment={d.get('comment', cfg.name)}",
        f"Exec={cfg.exe_name}",
        f"Icon={icon_name}",
        f"Categories={d.get('categories', 'Game;')}",
        "Terminal=false",
    ]
    (out / f"{app_id}.desktop").write_text("\n".join(desktop) + "\n", encoding="utf-8")
    return out


def _write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return
    path.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------

def _run(cmd: list, **kw) -> None:
    logger.info("run: %s", " ".join(str(c) for c in cmd))
    subprocess.run([str(c) for c in cmd], check=True, **kw)


def build_native(cfg: Config) -> None:
    """このマシン (またはコンテナ内) のツールチェインで configure/build/install。"""
    vcpkg = os.environ.get("VCPKG_ROOT")
    if not vcpkg:
        sys.exit("VCPKG_ROOT が未設定です")
    myapp = gen_myapp_cmake(cfg)
    cm = cfg.raw.get("cmake", {})
    args = [
        "cmake", "-S", BUILD_SYSTEM_DIR, "-B", cfg.cmake_dir, "-G", "Ninja Multi-Config",
        f"-DCMAKE_TOOLCHAIN_FILE={vcpkg}/scripts/buildsystems/vcpkg.cmake",
        f"-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE={vcpkg}/scripts/toolchains/linux.cmake",
        "-DVCPKG_CRT_LINKAGE=dynamic", "-DVCPKG_LIBRARY_LINKAGE=static",
        f"-DVCPKG_TARGET_TRIPLET={cfg.preset_triplet}",
        f"-DVCPKG_TARGET_ARCHITECTURE={cfg.arch}",
        "-DCMAKE_CXX_STANDARD=17", "-DCMAKE_CXX_STANDARD_REQUIRED=ON",
        f"-DKRKRZ_BASE={cfg.krkrz_base}",
        f"-DMYAPP_CMAKE_FILE={myapp}",
        f"-DKRKRZ_EXE_NAME={cfg.exe_name}",
    ]
    for k, v in cm.get("options", {}).items():
        args.append(f"-D{k}={cfg.expand(str(v))}")
    _run(args)
    _run(["cmake", "--build", cfg.cmake_dir, "--config", cfg.build_type])
    if cfg.install_dir.exists():
        shutil.rmtree(cfg.install_dir)
    _run(["cmake", "--install", cfg.cmake_dir, "--config", cfg.build_type,
          "--prefix", cfg.install_dir])


def build_in_container(cfg: Config) -> None:
    """steamdev deckbuild の sniper SDK イメージで build_native を実行する。

    パスはホストと同じ絶対パスでマウントするので、生成物のパスがそのまま通る。
    cmake のビルドツリーは named volume (bind mount の遅い I/O を避ける)。
    """
    image = os.environ.get("KRKRZ_LINUX_IMAGE", DEFAULT_IMAGE)
    mounts: list = []
    for p in sorted({cfg.krkrz_base, BUILD_SYSTEM_DIR, cfg.project_dir}, key=lambda x: len(str(x))):
        if not any(p == m or m in p.parents for m in mounts):
            mounts.append(p)
    cfg.cmake_dir.mkdir(parents=True, exist_ok=True)   # マウントポイントを root 所有にしない
    vol = "krkrz-linux-build-" + hashlib.sha1(str(cfg.cmake_dir).encode()).hexdigest()[:12]
    uid, gid = os.getuid(), os.getgid()
    inner = (
        f"mkdir -p /cache/vcpkg-bincache && "
        f"python3 {BUILD_SYSTEM_DIR}/tools/krkrz_linux.py build; rc=$?; "
        # コンテナは root で動くので、ソース側に出たファイルの所有者を戻す
        f"chown -R {uid}:{gid} {cfg.generated_dir} {cfg.install_dir} 2>/dev/null; exit $rc"
    )
    cmd = ["docker", "run", "--rm"]
    for m in mounts:
        cmd += ["-v", f"{m}:{m}"]
    cmd += [
        "-v", f"{vol}:{cfg.cmake_dir}",
        "-v", f"{CACHE_VOLUME}:/cache",
        "-e", "VCPKG_DEFAULT_BINARY_CACHE=/cache/vcpkg-bincache",
        "-e", "CC=gcc-14", "-e", "CXX=g++-14",
        "-e", f"KRKRZ_BASE={cfg.krkrz_base}",
        "-e", f"PROJECT_DIR={cfg.project_dir}",
        "-e", f"{IN_CONTAINER_ENV}=1",
        "-w", str(BUILD_SYSTEM_DIR),
        image, "bash", "-c", inner,
    ]
    _run(cmd)


def cmd_build(cfg: Config, native: bool) -> None:
    if native or os.environ.get(IN_CONTAINER_ENV):
        build_native(cfg)
    else:
        gen_myapp_cmake(cfg)
        build_in_container(cfg)


# ---------------------------------------------------------------------------
# stage / package
# ---------------------------------------------------------------------------

def cmd_stage(cfg: Config) -> Path:
    if not (cfg.install_dir / cfg.exe_name).is_file():
        sys.exit(f"ビルド成果物がありません ({cfg.install_dir}/{cfg.exe_name})。先に build を実行してください")
    gen = gen_package_files(cfg)
    ap = cfg.raw.get("assetPack", {})
    base = Path(cfg.expand(ap.get("baseFolder", "${PROJECT_DIR}")))
    # 先勝ち: エンジン一式 → 生成物 (.cf/.desktop/アイコン) → 案件の assetPack
    sources = [
        {"type": "mirror", "from": str(cfg.install_dir), "to": ""},
        {"type": "mirror", "from": str(gen), "to": ""},
    ] + list(ap.get("sources", []))
    stats = stage_engine.run_copy_rules(sources, cfg.package_dir, base, cfg.ctx)
    logger.info("staged %d files into %s (linked %d / copied %d / unchanged %d / removed %d)",
                stats["total"], cfg.package_dir, stats["linked"], stats["copied"],
                stats["unchanged"], stats["removed"])
    return cfg.package_dir


def cmd_package(cfg: Config) -> None:
    formats = cfg.raw.get("package", {}).get("formats", ["dir", "tar"])
    if not cfg.package_dir.is_dir():
        sys.exit("package フォルダがありません。先に stage を実行してください")
    if "tar" in formats:
        cfg.dist_dir.mkdir(parents=True, exist_ok=True)
        arch = {"x64": "x86_64", "arm64": "aarch64"}[cfg.arch]
        out = cfg.dist_dir / f"{cfg.exe_name}-{cfg.version}-linux-{arch}.tar.gz"
        def anon(ti: tarfile.TarInfo) -> tarfile.TarInfo:
            # 作業者のユーザー名を配布物に残さない
            ti.uid = ti.gid = 0
            ti.uname = ti.gname = ""
            return ti
        with tarfile.open(out, "w:gz") as tf:
            tf.add(cfg.package_dir, arcname=cfg.exe_name, filter=anon)
        logger.info("wrote %s", out)
    for f in formats:
        if f not in ("dir", "tar"):
            logger.warning("package format %r is not implemented yet", f)


def cmd_clean(cfg: Config) -> None:
    vol = "krkrz-linux-build-" + hashlib.sha1(str(cfg.cmake_dir).encode()).hexdigest()[:12]
    subprocess.run(["docker", "volume", "rm", vol], capture_output=True)
    if cfg.out_dir.exists():
        shutil.rmtree(cfg.out_dir)
    logger.info("removed %s (and docker volume %s)", cfg.out_dir, vol)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["all", "build", "stage", "package", "gen", "clean"])
    ap.add_argument("--native", action="store_true",
                    help="コンテナを使わずこのマシンでビルドする (参考ビルド。配布物は sniper で作ること)")
    a = ap.parse_args()
    cfg = Config()
    if a.command == "gen":
        gen_myapp_cmake(cfg)
        gen_package_files(cfg)
    elif a.command == "build":
        cmd_build(cfg, a.native)
    elif a.command == "stage":
        cmd_stage(cfg)
    elif a.command == "package":
        cmd_package(cfg)
    elif a.command == "clean":
        cmd_clean(cfg)
    elif a.command == "all":
        cmd_build(cfg, a.native)
        cmd_stage(cfg)
        cmd_package(cfg)


if __name__ == "__main__":
    main()
